### ISSUE TITLE
Plugin crashes on Ubuntu

### ISSUE THREAD

**Issue by udiudi** [UnwrittenFun/svelte-vscode#67]
Hi there.
Immediately when I open a Svelte file, the language server crashes with this error:

```shell
Error: Cannot find module './importResolvers/NodeModulesImportResolver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/udi/.vscode/extensions/ardenivanov.svelte-intellisense-0.6.0/server/out/server.js:21:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[Info  - 1:58:58 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:584
    throw err;
```

I've tried to re-install the plugin, and still same error occurs.
same setup works great on MacOS.

Any suggestions?

Thanks!

**Comment by jamesbirtles** [comment]
```
at Object.<anonymous> (/home/udi/.vscode/extensions/ardenivanov.svelte-intellisense-0.6.0/server/out/server.js:21:35)
```

Seems like that isn't coming from this plugin and instead from `ardenivanov.svelte-intellisense`

**Comment by udiudi** [comment]
Well, this is awkward O.O
Apologies, and thanks!

**Comment by adolfojbarreto** [comment]
Lol, @udiudi that happened to me as well. **I'm happy I wasn't alone!** Thanks @UnwrittenFun
